### ISSUE TITLE
Dev artefact left

### ISSUE THREAD

**Issue by kabalin** [davosmith/moodle-realtimequiz#6]
Davo, it seems like tests/behat/attemptquiz.feature contains work in progress tag (wip). I spotted that while designing and running a test at another part of Moodle.

**Comment by davosmith** [comment]
Sorry, I checked that one in by mistake (I know how much it annoys me when other devs leave them in - and also how easy it is to leave it in when you finally get a test to pass).

All gone now (and thanks for the bug report).
