### ISSUE TITLE
'object' class has been deprecated

### ISSUE THREAD

**Issue by ewallah** [davosmith/moodle-realtimequiz#7]
Debugging: 'object' class has been deprecated, please use stdClass instead. in 
* line 71 of /lib/setuplib.php: call to debugging()
* line 70 of /mod/realtimequiz/quizdata.php: call to object->__construct()
referer: mod/realtimequiz/view.php?id=185000

Moodle 3.3.1+ (Build: 20170810)
Php: 7.1.8.2.16.04.1.4, 
pgsql: 9.5.7, 
OS: Linux 4.4.0-91-generic x86_64

Detected while running behat testing.

**Comment by davosmith** [comment]
Thanks for the report - I've fixed it here on github and will push it out to Moodle.org when I next do a release.
