### ISSUE TITLE
Unsupported $module syntax

### ISSUE THREAD

**Issue by ewallah** [davosmith/moodle-realtimequiz#8]
Providing support for pre Moodle 2.6 versions breaks behat and phpunit functionality:

`++ Unsupported $module syntax detected in version.php of the mod_realtimequiz plugin. ++
* line 309 of /lib/classes/plugin_manager.php: call to debugging()
* line 335 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
* line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
* line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
* line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
* line 395 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
* line 43 of /admin/settings/plugins.php: call to core_plugin_manager->get_plugins_of_type()
* line 7999 of /lib/adminlib.php: call to require()
* line 8020 of /lib/adminlib.php: call to admin_get_root()
* line 1647 of /lib/upgradelib.php: call to admin_apply_default_settings()
* line 481 of /lib/installlib.php: call to install_core()
* line 86 of /lib/behat/classes/util.php: call to install_cli_database()
* line 160 of /admin/tool/behat/cli/util_single_run.php: call to behat_util::install_site()`

Perhaps the support for these OLD versions can be dropped as an incentive to upgrade their software?

**Comment by davosmith** [comment]
Yes I am aware of this bug in Moodle core that incorrectly mis-identifies the presence of $moodle in the version.php.

Thankfully this only occurs during install, so should not cause any failures whilst the test are running.

**Comment by ewallah** [comment]
My behat tests are also failing on 

`And I press "Next"`

Especially when the language file has this line:

`$string['next'] = 'Next >>';`

**Comment by davosmith** [comment]
I don't get that - I ran all the Behat tests against Moodle 3.4 last week and they all passed (using selenium + phantomjs).
